info:
  component:  Server
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true

ribbon:
  eureka:
    enabled: true
    
server:
  port: 8085
spring:
  application:
    name: server
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          strategy: THREAD
#          thread:
#            timeoutInMilliseconds: 60000
    
zuul:
  prefix: 
  routes:
    login: 
      path: /security/**
      serviceId: user-service
    task: 
      path: /**
      serviceId: task-service
